### ISSUE TITLE
ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by sysadmin-info** [Aaahh/conky-spotify#1]
After conversion to modern conky this part:

conky.config = {

	--Various settings

	update_interval = 1,						-- update interval
	total_run_times = 0,						-- total run times
	double_buffer = true,						-- Use the Xdbe extension? (eliminates flicker)
	text_buffer_size = 2048,					-- size of buffer for display of content of large variables - default 256
	imlib_cache_size = 0,                       -- disable image cache to get a new spotify cover per song

	--Placement

	alignment = 'top_right',					-- top_left,top_middle,top_right,bottom_left,bottom_middle,bottom_right,
                                  				-- middle_left,middle_middle,middle_right,none
    gap_x = 70,									-- pixels between right or left border
	gap_y = 75,									-- pixels between bottom or left border
	minimum_height = 90,						-- minimum height of window
	minimum_width = 300,						-- minimum width of window
	maximum_width = 400,						-- maximum height of window

	--Graphical

	draw_borders = false,						-- draw borders around text
	draw_graph_borders = false,				 	-- draw borders around graphs
	draw_shades = false,						-- draw shades
	draw_outline = false,						-- draw outline

	-- Textual
	use_xft = true,								-- xft font - anti-aliased font
	xftalpha = 1,								-- alpha of the xft font - between 0-1
	font = 'Droid Sans:size=8',           		-- font for complete conky unless in code defined

	-- Window

	own_window = true,							-- create your own window to draw.
	own_window_argb_value = 0,					-- real transparency - composite manager required 0-255
	own_window_argb_visual = true,				-- use ARGB - composite manager required
	own_window_transparent = true,				-- if own_window_argb_visual is true sets background opacity 0%
	own_window_class = 'desktop	',				-- manually set the WM_CLASS name for use with xprop
	own_window_type = 'override',				-- if own_window true options are: normal/override/dock/desktop/panel
	own_window_colour = '000000',				-- set colour if own_window_transparent no	
	own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager',  -- if own_window true - just hints - own_window_type sets it

	--Colours

	color0 = 'FFFFFF',
	color1 = 'E6E6E6',
	color2 = '1A1A1A',
	color3 = '000000',

};

conky.text = [[
${if_running spotify}
${image $HOME/.config/conky/latest.jpg -p 210/0,0 -s 90x90}
${voffset 5}${color0}${font LL_Record:size=14}${goto 10}d${font Droid Sans:size=14}${color0}${goto 40}${voffset 10}${execpi 2 python $HOME/.config/conky/spotify_getinfo.py}
${endif}
]];

The part below in line 32 has an issue:

  File "/home/adrian/.config/conky/spotify_getinfo.py", line 32, in <module>
    if (float(avgColor[0])*0.299 + float(avgColor[1])*0.587 + float(avgColor[2])*0.114) > 186:
ValueError: could not convert string to float: '12.8523%'

I have no idea is it related to python 3 , but it would be nice to correct the python code.

#!/usr/bin/python

import os

def perfect_length(str):
	if len(str) > 23:
		return str[:21] + '...'
	else:
		return str

playing_song = os.popen("dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n \'/title/{n;p}\' | cut -d \'\"\' -f 2|tr -d '\n'").read()
playing_artist = os.popen("dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n \'/artist/{n;n;p}\' | cut -d \'\"\' -f 2|tr -d '\n'").read()
playing_album = os.popen("dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n \'/album\"/{n;p}\' | cut -d \'\"\' -f 2| cut -d' ' -f-6 | tr -d '\n'").read()
artworkUrl= os.popen("dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n \'/artUrl/{n;p}\' | cut -d \'\"\' -f 2|tr -d '\n'").read()

fle=os.popen("/usr/bin/gsettings get org.gnome.desktop.background picture-uri").read()
fle=fle.replace("\n", " ")
fstored_album = open(os.getenv('HOME') + '/.config/conky/stored_album.txt', 'r')
stored_album = fstored_album.readlines()
fstored_album.close()

if (playing_album+fle).strip('\n') != stored_album[0].strip('\n'):
	# New cover needs to be downloaded
	os.system("wget -O $HOME/.config/conky/latest.jpg https://i.scdn.co/image/" + artworkUrl[31:])
	# If you'd like download a cover 174x174 instead of 64x64 use this one instead:no
	# os.system("wget -O $HOME/.config/conky/latest.jpg \"http://interactiveplaylist.com/ipfal?album=" + playing_album + "&artist=" + playing_artist + "\"")
	#quailty code
	size=os.popen(("identify "+fle)).read().split(" ")[2].split("x")
	wall_height=int(size[0])
	wall_width=(wall_height/1920)*400
	avgColor=os.popen("convert "+fle+" -crop " + str(wall_width) + "x"+ str((int(size[1])/1080)*300) +"+"+str(wall_height-wall_width)+"+""15 -scale 1x1\\! txt:-").read()[1:].split("(")[2][:-2].split(",")
	if (float(avgColor[0])*0.299 + float(avgColor[1])*0.587 + float(avgColor[2])*0.114) > 186:
		colora=str(3)
		coloraa=str(2)
	else:
		colora=str(0)
		coloraa=str(1)
	# Update current_song.txt using bash 380*150
	os.system("echo \"" + ((playing_album + fle).strip('\n')+"\n"+colora+"\n"+coloraa) + "\" > $HOME/.config/conky/stored_album.txt")
	#1475
else:
	colora=str(stored_album[1]).strip("\n")
	coloraa=str(stored_album[2]).strip("\n")

print("${color"+colora+"}${font LL_Record:size=14}${goto 10}d${font}${color"+coloraa+"}${goto 40}${voffset -8}" + perfect_length(playing_song) + "\n${goto 40}" + perfect_length(playing_artist))

**Comment by mmhobi7** [comment]
Add [:-1] to the end of the the stuff in the float parentheses, so like
float(blaaaah[:-1])
Just a guess

**Comment by sysadmin-info** [comment]
When I changed this the way you mentioned:

if (float(avgColor[:-0])*0.299 + float(avgColor[:-1])*0.587 + float(avgColor[:-2])*0.114) > 186:
		colora=str(3)
		coloraa=str(2)
	else:

I have an error:

  File "/home/adrian/.config/conky/spotify_getinfo.py", line 32, in <module>
    if (float(avgColor[:-0])*0.299 + float(avgColor[:-1])*0.587 + float(avgColor[:-2])*0.114) > 186:
TypeError: float() argument must be a string or a number, not 'list'

**Comment by mmhobi7** [comment]
What no i meant

if (float(avgColor[0][:-1])*0.299 + float(avgColor[1][:-1])*0.587 +
float(avgColor[2][:-1])*0.114) > 186:

**Comment by sysadmin-info** [comment]
Thanks. Issue solved. I can do the fork if you wish, or you can do the new branch. With the code I provided above.

**Comment by mmhobi7** [comment]
Yeah could you send fork and send me a pull request ?

**Comment by sysadmin-info** [comment]
https://github.com/sysadmin-info/conky-spotify
